/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_video_android_c_object_MainActivity */

#ifndef _Included_com_example_video_android_c_object_MainActivity
#define _Included_com_example_video_android_c_object_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_video_android_c_object_MainActivity
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_video_android_1c_1object_MainActivity_getStringFromNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
